"""
Rebuild ALL_COMBOS dict from cache/massive_scan_results.csv.

Reads the scan results CSV and emits a Python snippet (cache/all_combos_snippet.py)
ready to paste into challenge_decks.py.

Looks up preset params from massive_scan.STRATEGIES (the canonical source).

Usage:
    python -X utf8 scripts/rebuild_all_combos.py
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import pandas as pd
from scripts.massive_scan import STRATEGIES


def main():
    csv_path = Path("cache/massive_scan_results.csv")
    if not csv_path.exists():
        print(f"ERROR: {csv_path} does not exist. Run massive_scan.py first.")
        return

    df = pd.read_csv(csv_path)
    print(f"Loaded {len(df)} combos from {csv_path}")

    out_path = Path("cache/all_combos_snippet.py")
    missing = []
    with out_path.open("w", encoding="utf-8") as f:
        f.write("# Auto-generated by rebuild_all_combos.py\n")
        f.write("# Source: cache/massive_scan_results.csv (REALISTIC FTMO spreads)\n")
        f.write("# Paste into scripts/challenge_decks.py replacing ALL_COMBOS.\n\n")
        f.write("ALL_COMBOS = {\n")

        for _, row in df.iterrows():
            strat = row["strat"]
            preset = row["preset"]
            symbol = row["symbol"]
            combo_name = row["combo"]
            tier = row["tier"]
            pf = float(row["pf"])

            info = STRATEGIES.get(strat)
            if info is None:
                missing.append((combo_name, "strat not in STRATEGIES"))
                continue
            preset_params = info["presets"].get(preset)
            if preset_params is None:
                missing.append((combo_name, f"preset '{preset}' not in {strat}"))
                continue

            params = {**preset_params}
            params.setdefault("session_start", 0)
            params.setdefault("session_end", 23)

            f.write(f'    "{combo_name}": {{\n')
            f.write(f'        "strat": "{strat}", "symbol": "{symbol}", '
                    f'"tier": "{tier}", "pf": {pf:.2f},\n')
            f.write(f'        "params": {repr(params)},\n')
            f.write(f'    }},\n')

        f.write("}\n")

    print(f"\nWrote {out_path}")
    if missing:
        print(f"\nWARNING: {len(missing)} combos could not be reconstructed:")
        for c, why in missing:
            print(f"  {c}: {why}")
    else:
        print(f"All {len(df)} combos reconstructed successfully.")


if __name__ == "__main__":
    main()
